apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod-route53
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: admin@devopsr66.com
    privateKeySecretRef:
      name: letsencrypt-prod-route53
    solvers:
    - dns01:
        route53:
          region: us-east-1
          hostedZoneID: "Z0603299CCGZS6N8JJX9"
          accessKeyIDSecretRef:
            name: route53-credentials-secret
            key: access-key-id
          secretAccessKeySecretRef:
            name: route53-credentials-secret
            key: secret-access-key
